icat:
  url: https://localhost:8181
  check_cert: False
  facility_name: LILS
  create_parameter_types: true
  functional_user:
    auth: simple
    username: root
    password: pw
  admin_users:
    - auth: simple
      username: root

fts3:
  endpoint: https://lcgfts3.gridpp.rl.ac.uk:8446
  instrument_data_cache: root://idc.ac.uk:1094//
  restored_data_cache: root://rdc.ac.uk:1094//
  tape_archive: root://archive.ac.uk:1094//
  x509_user_cert: hostcert.pem
  x509_user_key: hostkey.pem

s3:
  endpoint: http://localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  cache_bucket: cache-bucket